[package]
name = "polylabel_cmd"
version = "0.0.1"
authors = ["Stephan Hügel <urschrei@gmail.com>"]
description = "A command-line utility for finding optimum polygon label positions"
readme = "README.md"
keywords = ["geo, polylabel, gis"]
license = "MIT"

[dependencies]
geo = "0.6.2"
geojson = "0.9.1"
polylabel = "1.0.44"
clap = "2.29.0"

[[bin]]
name = "polylabel"
path = "src/main.rs"
crate-type = ["bin"]

[[bin]]
name = "pt_test"
path = "src/pt_test.rs"
crate-type = ["bin"]

[profile.release]
lto = true