[package]
name = "polylabel_cmd"
version = "0.0.28"
authors = ["Stephan Hügel <urschrei@gmail.com>"]
description = "A command-line utility for finding optimum polygon label positions"
readme = "README.md"
repository = "https://github.com/urschrei/polylabel_cmd"
keywords = ["geo", "polylabel", "gis"]
license = "MIT"
exclude = ["geojson/*"]

[dependencies]
geo = "0.6.2"
geojson = "0.9.1"
polylabel = "1.0.44"
clap = "2.29.1"
serde_json = "1.0.8"
rayon = "1.0.0"
failure = "0.1.1"
failure_derive = "0.1.1"
console = "0.6.1"
indicatif = "0.9.0"

[[bin]]
name = "polylabel"
path = "src/main.rs"

[profile.release]
lto = true
codegen-units = 1
